[Interface]
PrivateKey = UFm3nqvjaeSZxXoYMR9cHlxYBXQteDX9ljLeZq2F4XQ=
Address = 10.66.66.2/32,fd42:42:42::2/128
DNS = 1.1.1.1,1.0.0.1

# Uncomment the next line to set a custom MTU
# This might impact performance, so use it only if you know what you are doing
# See https://github.com/nitred/nr-wg-mtu-finder to find your optimal MTU
# MTU = 1420

[Peer]
PublicKey = lnq6nzMvAQX9kcae783Q02xd2fC1MGLdjwDx00/8LRM=
PresharedKey = NyA2/XK7J1S7pbgT0eF9zYpKMfQKb1/PGn3sUuBgry8=
Endpoint = ali.elhaji-Mumbai-wg0-client-user1.conf.mywireguard.com:61945
AllowedIPs = 0.0.0.0/0,::/0
