[Interface]
Address = 10.66.66.1/24,fd42:42:42::1/64
ListenPort = 61945
PrivateKey = sI1vwPCvizZFTgxAv7BlpajP9PMPNGeCtEznRjbqDVM=
PostUp = iptables -I INPUT -p udp --dport 61945 -j ACCEPT
PostUp = iptables -I FORWARD -i ens5 -o wg0 -j ACCEPT
PostUp = iptables -I FORWARD -i wg0 -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o ens5 -j MASQUERADE
PostUp = ip6tables -I FORWARD -i wg0 -j ACCEPT
PostUp = ip6tables -t nat -A POSTROUTING -o ens5 -j MASQUERADE
PostDown = iptables -D INPUT -p udp --dport 61945 -j ACCEPT
PostDown = iptables -D FORWARD -i ens5 -o wg0 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o ens5 -j MASQUERADE
PostDown = ip6tables -D FORWARD -i wg0 -j ACCEPT
PostDown = ip6tables -t nat -D POSTROUTING -o ens5 -j MASQUERADE

### Client user1
[Peer]
PublicKey = 7YYVPgxia/Dt43MYwO55U44Cj5YHTrYafxIJew06+kQ=
PresharedKey = NyA2/XK7J1S7pbgT0eF9zYpKMfQKb1/PGn3sUuBgry8=
AllowedIPs = 10.66.66.2/32,fd42:42:42::2/128
